### PR TITLE
Update from debian:jessie to ubuntu:20.04 in Dockerfile

### PR DESCRIPTION
**Pull request by schast**
Changes in Dockerfile:
- update from debian:jessie to ubuntu:20.04
- update php packages from 5 to 7.4
- set upload_max_filesize and post_max_size to 16GB
- Add some build args to Dockerfile

Changes in admidio_apache.conf:
- Write logfiles directly to docker stdout and stderr

### CODE REVIEW

**Comment by Fasse** [comment]
@schast Thanks for your contribution. Since I personally have no knowledge of Docker, I write to @Brawn1 if he could review your changes.

**Comment by schast** [comment]
@Fasse if you want and give me the necessary access rights, I could take over the maintenance of `https://hub.docker.com/r/admidio/admidio/`, configure and activate autobuild to get out of the box usable docker images.

**Comment by Fasse** [comment]
@schast That sounds interesting. Maybe you write me to the email address in our imprint https://www.admidio.org/imprint.php

**Comment by ximex** [comment]
shouldn't we also add `php7.4-mbstring`, `php7.4-imap`, `php7.4-json`?
and isn't `php7.4` also installing `libapache2-mod-php7.4`, `php7.4-common` automatically?

**Pull request merged**
